language: cpp
sudo: false

script:
- git clone --branch release-1.10.0 --depth 1 https://github.com/google/googletest.git
- cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=1 .
- cmake --build . --config Release
- if [[ "$(uname)" == "Linux" ]]; then LD_LIBRARY_PATH=. LD_PRELOAD=liboverthrower.so ./overthrower_tests; fi
- if [[ "$(uname)" == "Darwin" ]]; then DYLD_FORCE_FLAT_NAMESPACE=1 DYLD_INSERT_LIBRARIES=./overthrower.framework/Versions/Current/overthrower ./overthrower_tests; fi


matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - os: linux
      dist: focal
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode9
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode10
    - os: osx
      osx_image: xcode10.3
    - os: osx
      osx_image: xcode11
    - os: osx
      osx_image: xcode11.6
