language: cpp

script:
  - ./test.sh

env:
  - MEASURE_COVERAGE=1

matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - os: linux
      dist: focal
    - os: linux
      dist: bionic
    - os: linux
      dist: focal

    - os: linux
      dist: trusty
      env:
        - USE_LIBUNWIND=1
        - MEASURE_COVERAGE=1
    - os: linux
      dist: xenial
      env:
        - USE_LIBUNWIND=1
        - MEASURE_COVERAGE=1
    - os: linux
      dist: bionic
      env:
        - USE_LIBUNWIND=1
        - MEASURE_COVERAGE=1
    - os: linux
      dist: focal
      env:
        - USE_LIBUNWIND=1
        - MEASURE_COVERAGE=1
    - os: linux
      dist: bionic
      env:
        - USE_LIBUNWIND=1
        - MEASURE_COVERAGE=1
    - os: linux
      dist: focal
      env:
        - USE_LIBUNWIND=1
        - MEASURE_COVERAGE=1

    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode10.3
    - os: osx
      osx_image: xcode11.6
    - os: osx
      osx_image: xcode12
