language: cpp

env:
  - CMAKE_BUILD_TYPE=Release

script:
- git clone --branch release-1.10.0 --depth 1 https://github.com/google/googletest.git
- cmake -DCMAKE_C_FLAGS="${CMAKE_C_FLAGS}" -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS}" -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}" -DCMAKE_VERBOSE_MAKEFILE=1 .
- cmake --build . --config Release
- if [[ "$(uname)" == "Linux" ]]; then LD_LIBRARY_PATH=. LD_PRELOAD=liboverthrower.so ./overthrower_tests; fi
- if [[ "$(uname)" == "Darwin" ]]; then DYLD_FORCE_FLAT_NAMESPACE=1 DYLD_INSERT_LIBRARIES=./overthrower.framework/Versions/Current/overthrower ./overthrower_tests; fi
- if [[ "${MEASURE_COVERAGE}" == "1" ]]; then
    ${LLVM_PROFDATA} merge -sparse default.profraw -o default.profdata;
    ${LLVM_COV} show ${OVERTHROWER_LIBRARY_PATH} -instr-profile=default.profdata -Xdemangler=c++filt;
    ${LLVM_COV} report ${OVERTHROWER_LIBRARY_PATH} -instr-profile=default.profdata;
  fi

matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - os: linux
      dist: focal
    - os: linux
      dist: focal
      env:
        - MEASURE_COVERAGE=1
        - OVERTHROWER_LIBRARY_PATH=./liboverthrower.so
        - CC=clang
        - CXX=clang++
        - LLVM_PROFDATA=llvm-profdata
        - LLVM_COV=llvm-cov
        - CMAKE_C_FLAGS="-fprofile-instr-generate -fcoverage-mapping"
        - CMAKE_CXX_FLAGS="-fprofile-instr-generate -fcoverage-mapping"
        - CMAKE_BUILD_TYPE=Debug
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode9
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode10
    - os: osx
      osx_image: xcode10.3
    - os: osx
      osx_image: xcode11
    - os: osx
      osx_image: xcode11.6
    - os: osx
      osx_image: xcode11.6
      env:
        - MEASURE_COVERAGE=1
        - OVERTHROWER_LIBRARY_PATH=./overthrower.framework/Versions/Current/overthrower
        - LLVM_PROFDATA="xcrun llvm-profdata"
        - LLVM_COV="xcrun llvm-cov"
        - CMAKE_C_FLAGS="-fprofile-instr-generate -fcoverage-mapping"
        - CMAKE_CXX_FLAGS="-fprofile-instr-generate -fcoverage-mapping"
        - CMAKE_BUILD_TYPE=Debug
