language: cpp

script:
- cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=1 .
- cmake --build . --config Release
- python ./tests/test.py

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: false
        - os: osx
          osx_image: xcode8
